### ISSUE TITLE
Unable to Delete Certain Albums

### ISSUE THREAD

**Issue by DirtyOldMan66** [LusciousMedia/luscious#17] opened 2016-12-12 03:23 UTC
I've come across several albums with no content. Normally, I can easily delete these. When I've tried to do it lately, though, I get a white screen that tells me I need to do it via "post" (can't remember the exact working, but hopefully this makes sense).

**Comment by KaySackey** [comment] 2017-01-19 17:01
That was caused by the JS not including on the page, so the click just was sent normally. It's expected, but should be fixed now.

**Closed by KaySackey** 2017-01-19 17:01 UTC
